shopping/urls.py
from django.contrib import admin
from django.urls import path,include
from product.views import HomeView, ProductDetailView, store,check,add_to_cart,remove_from_cart,OrderSummaryView,remove_single_from_cart,add_single_from_cart,checkout,finalorder,search
from django.conf import settings
from django.conf.urls.static import static
app_name = 'product'
urlpatterns = [
    path('search/',search, name='search'),
    path('admin/', admin.site.urls),
    path('', HomeView.as_view(),name='home'),
    path('accounts/', include('allauth.urls')),
    path('order-summary/',OrderSummaryView.as_view(), name='order-summary'),
    path('product/<slug>/', ProductDetailView.as_view(), name='p-detail'),
    path('store/', store),
    path('checkout/',checkout, name="checkout"),
   
    path('final-order/', finalorder, name='final_order'),
    path('checkout/',check ,name='checkout'),
    path('add-to-cart/<slug>/',add_to_cart ,name='add_to_cart'),
    path('remove-single-item-from-cart/<slug>/',remove_single_from_cart ,name='remove_single_from_cart'),
    path('add-single-item-to-cart/<slug>/',add_single_from_cart ,name='add_single_from_cart'),
    path('remove-from-cart/<slug>/',remove_from_cart ,name='remove_from_cart')
]

if settings.DEBUG:
	urlpatterns+=static(settings.STATIC_URL,document_root=settings.STATIC_ROOT)
	urlpatterns+=static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT) 

product/models.py
from django.db import models
from django.contrib.auth import get_user_model
from django.urls import reverse
from django.conf import settings



LABEL_CHOICES=(
	('P','primary'),
	('S','secondary'),
	('D','danger'),
)

class Category(models.Model):
	title=models.CharField(max_length=20)

	def __str__(self):
		return self.title


class Product(models.Model):
	title=models.CharField(max_length=100)
	overview=models.TextField()
	timestamp=models.DateTimeField(auto_now_add=True)
	thumbnail=models.ImageField()
	categories=models.ManyToManyField(Category)
	label=models.CharField(choices=LABEL_CHOICES,max_length=1)
	price=models.IntegerField()
	slug=models.SlugField()

	def __str__(self):
		return self.title

	def get_absolute_url(self):
		return reverse('p-detail',kwargs={
			'slug':self.slug
		})

	def get_add_to_cart_url(self):
		return reverse('add_to_cart',kwargs={
			'slug':self.slug
		})	

	def get_remove_from_cart_url(self):
		return reverse('remove_from_cart',kwargs={
			'slug':self.slug
		})	

class OrderItem(models.Model):
	user=models.ForeignKey(settings.AUTH_USER_MODEL,on_delete=models.CASCADE)
	item=models.ForeignKey(Product,on_delete=models.CASCADE)
	quantity=models.IntegerField(default=1)
	ordered=models.BooleanField(default=False)
	def __str__(self):
		return f"{self.quantity} of {self.item.title}"

	def get_total_price(self):
		return self.quantity*self.item.price

	def get_final_price(self):
		return self.get_total_price()




class Order(models.Model):
	user=models.ForeignKey(settings.AUTH_USER_MODEL,on_delete=models.CASCADE)
	items=models.ManyToManyField(OrderItem)
	start_date=models.DateTimeField(auto_now_add=True)
	ordered_date=models.DateTimeField()
	ordered=models.BooleanField(default=False)
	
	def __str__(self):
		return self.user.username

	def get_total(self):
		total=0
		for order_item in self.items.all():
			total+= order_item.get_final_price()
		return total

class CheckOut(models.Model):
	name=models.CharField(max_length=40)
	email=models.EmailField()
	address=models.TextField()
	country=models.CharField(max_length=20)
	zipcode=models.IntegerField()
	contactno=models.IntegerField()

	def __str__(self):
		return self.name

product/forms.py
from django import forms
from product.models import CheckOut
class CheckoutForm(forms.ModelForm):
    class Meta:
        model=CheckOut
        fields='__all__'
        

product/views.py
from django.contrib import messages
from django.core.exceptions import ObjectDoesNotExist,MultipleObjectsReturned
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.shortcuts import render,get_object_or_404,redirect,reverse
from django.views.generic import ListView,DetailView,View
from product.models import Category,Product,Order,OrderItem,CheckOut
from .forms import CheckoutForm
from django.utils import timezone
from django.db.models import Count, Q
from django.core.mail import send_mail



def search(request):
	queryset=Product.objects.all()
	query=request.GET.get('q')
	if query:
		queryset=queryset.filter(
			Q(title__icontains=query) |
			Q(overview__icontains=query)
		).distinct()
	context={
		'queryset':queryset
	}
	return render(request,'search_results.html',context)





class HomeView(ListView):
    model=Product
    template_name="index.html"


class OrderSummaryView(LoginRequiredMixin,View):
    def get(self,*args,**kwargs):

        try:
            order=Order.objects.get(user=self.request.user, ordered=False)
            context={
                'object':order
            }
            return render(self.request,'order_summary.html',context)
        except ObjectDoesNotExist:
            messages.error(self.request,"You dont have an active order!")
            return redirect("/")


        



class ProductDetailView(DetailView):
    model=Product
    template_name="product.html"




def store(request):
    return render(request,'store.html',{})


@login_required
def check(request):
    
    order=Order.objects.get(user=request.user, ordered=False)
    context={
        'order':order
    }
    return render(request,'checkout.html',context)

@login_required
def finalorder(request):
    
    order=Order.objects.get(user=request.user, ordered=False)
    context={
        'order':order
    }
    return render(request,'almostcheck.html',context)
    

@login_required
def add_to_cart(request, slug):
    item = get_object_or_404(Product,slug=slug)
    order_item, created=OrderItem.objects.get_or_create(
        item=item,
        user=request.user,
        ordered=False
    )
    order_qs=Order.objects.filter(user=request.user,ordered=False)
    if order_qs.exists():
        order=order_qs[0]
        if order.items.filter(item__slug=item.slug).exists():
            order_item.quantity+=1
            order_item.save()
            messages.info(request,"This item quantity was updated!")
            return redirect("p-detail",slug=slug)
        else:

            order.items.add(order_item)
            messages.info(request,"This item was added!")
            return redirect("p-detail",slug=slug)
    else:
        ordered_date=timezone.now()
        order=Order.objects.create(user=request.user,ordered_date=ordered_date)
        order.items.add(order_item)
        messages.info(request,"This item was added!")
        return redirect("p-detail",slug=slug)

@login_required
def remove_from_cart(request, slug):
    item = get_object_or_404(Product,slug=slug)
    order_qs=Order.objects.filter(user=request.user,ordered=False)
    if order_qs.exists():
        order=order_qs[0]
        if order.items.filter(item__slug=item.slug).exists():
            order_item=OrderItem.objects.filter(
                item=item,
                user=request.user,
                ordered=False
            )[0]
            order.items.remove(order_item)
            messages.info(request,"This item was removed!")
            return redirect("p-detail",slug=slug) 
        else:
            messages.info(request,"Your order does not have this item!")
            return redirect("p-detail",slug=slug)

        
            
    else:
        messages.info(request,"You dont have any orders!")
        return redirect("p-detail",slug=slug)

@login_required
def remove_single_from_cart(request, slug):
    item = get_object_or_404(Product,slug=slug)
    order_qs=Order.objects.filter(user=request.user,ordered=False)
    if order_qs.exists():
        order=order_qs[0]
        if order.items.filter(item__slug=item.slug).exists():
            order_item=OrderItem.objects.filter(
                item=item,
                user=request.user,
                ordered=False
            )[0]
            if order_item.quantity>1:
                order_item.quantity-=1
                order_item.save()
            else:
                order.items.remove(order_item)

            messages.info(request,"Your order quantity was updated!")
            return redirect("order-summary") 
        else:
            messages.info(request,"Your order does not have this item")
            return redirect("p-detail",slug=slug)

        
            
    else:
        messages.info(request,"You dont have any orders!")
        return redirect("p-detail",slug=slug)


@login_required
def add_single_from_cart(request, slug):
    item = get_object_or_404(Product,slug=slug)
    order_qs=Order.objects.filter(user=request.user,ordered=False)
    if order_qs.exists():
        order=order_qs[0]
        if order.items.filter(item__slug=item.slug).exists():
            order_item=OrderItem.objects.filter(
                item=item,
                user=request.user,
                ordered=False
            )[0]
            order_item.quantity+=1
            order_item.save()
            messages.info(request,"Your order quantity was updated!")
            return redirect("order-summary") 
        else:
            messages.info(request,"Your order does not have this item")
            return redirect("p-detail",slug=slug)

        
            
    else:
        messages.info(request,"You dont have any orders!")
        return redirect("p-detail",slug=slug)


def checkout(request):
    orderr=Order.objects.get(user=request.user, ordered=False)
    form=CheckoutForm(request.POST or None)
    if form.is_valid():
        
        email = form.cleaned_data['email']
        name = form.cleaned_data['name']
        form.save()
        subject=f" Dear {name} , your order confirmation"
        send_mail(
            subject,
            'This is an automated email. Thankyou for ordering from Electro.Your order will be delivered soon. The payment method being COD.',
            'waze.atharva@yahoo.com',
            [email]
        
            )       
        form.save()
        try:
            Ord=Order.objects.get(user=request.user)
            Ord.ordered=True
            Ord.save()
            messages.info(request,"Your order has been placed successfully!")
        except(MultipleObjectsReturned):
            Ord=Order.objects.filter(user=request.user).order_by('id').last()
            Ord.ordered=True
            Ord.save()
            messages.info(request,"Your order has been placed successfully!")
        

        return redirect(reverse('home'))
        




    return render(request,'almostcheck.html',{
        'form':form,
        'order':orderr
    })


# def mail(request):
#     form=CheckoutForm(request.POST or None)
#     if form.is_valid():
#         email = form.cleaned_data['email']
#         name = form.cleaned_data['name']
#         subject='f" Dear {name} , your order confirmation"'
#         send_mail(
#             subject,
#             'This is an automated email. Thankyou for ordering from Electro.Your order will be delivered soon. The payment method being COD.',
#             'waze.atharva@yahoo.com',
#             [email]
#             )
#         return redirect(reverse('home'))


    

templates/almostcheck.html
{% extends 'base.html' %}
{% load static %}
{% load crispy_forms_tags %}

{% block content %}

					<!-- Order Details -->
                    <div class="section">
                        <!-- container -->
                        <div class="container">
                            <!-- row -->
                            <div class="row">
            
                                <div class="col-md-7">
                                
                                    <div class="billing-details">
                                        <div class="section-title">
                                            <h3 class="title">Billing address</h3>
                                        </div>
                                        <form method="POST" >
                                            {% csrf_token %}
                                            {{form|crispy}}
                
                                            <button class="primary-btn order-submit" type="submit">Place Order</button>
                                        </form>
                                
                                         <div class="form-group">
                                            <div class="input-checkbox">
                                                <input type="checkbox" id="create-account">
                                                <label for="create-account">
                                                    <span></span>
                                                    Create Account?
                                                </label>
                                                <div class="caption">
                                                    <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt.</p>
                                                    <input class="input" type="password" name="password" placeholder="Enter Your Password">
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                    <!-- /Billing Details -->
            
                                    <!-- Shiping Details -->
                                    <div class="shiping-details">
                                        <div class="section-title">
                                            
                                        </div>
                                        <div class="input-checkbox">
                                            <input type="checkbox" id="shiping-address">
                                            <!-- <label for="shiping-address">
                                                <span></span>
                                                Ship to a diffrent address?
                                            </label>
                                            <div class="caption">
                                                <div class="form-group">
                                                    <input class="input" type="text" name="first-name" placeholder="First Name">
                                                </div>
                                                <div class="form-group">
                                                    <input class="input" type="text" name="last-name" placeholder="Last Name">
                                                </div>
                                                <div class="form-group">
                                                    <input class="input" type="email" name="email" placeholder="Email">
                                                </div>
                                                <div class="form-group">
                                                    <input class="input" type="text" name="address" placeholder="Address">
                                                </div>
                                                <div class="form-group">
                                                    <input class="input" type="text" name="city" placeholder="City">
                                                </div>
                                                <div class="form-group">
                                                    <input class="input" type="text" name="country" placeholder="Country">
                                                </div>
                                                <div class="form-group">
                                                    <input class="input" type="text" name="zip-code" placeholder="ZIP Code">
                                                </div>
                                                <div class="form-group">
                                                    <input class="input" type="tel" name="tel" placeholder="Telephone">
                                                </div> -->
                                            </div>
                                        </div>
                                    </div>
                                    <!-- /Shiping Details -->
            
                                    
                                    <!-- <div class="order-notes">
                                        <textarea class="input" placeholder="Order Notes"></textarea>
                                    </div> -->
                                    <!-- /Order notes
                                </div>
            
                                 Order Details -->
                                <div class="col-md-5 order-details">
                                    <div class="section-title text-center">
                                        <h3 class="title">Your Order</h3>
                                    </div>
                                    <div class="order-summary">
                                        <div class="order-col">
                                            <div><strong>PRODUCT</strong></div>
                                            <div><strong>TOTAL</strong></div>
                                        </div>
                                        {% for order_item in order.items.all %}
                                        <div class="order-products">
                                            
                                            <div class="order-col">
                                                <div>{{order_item.quantity}}x {{order_item.item.title}}</div>
                                                <div>{{order_item.get_total_price}}</div>
                                            </div>
                                        </div>
                                        {% endfor %}
                                        
                                        {% if order.get_total %}
                                        <div class="order-col">
                                            <div>Shiping</div>
                                            <div><strong>FREE</strong></div>
                                        </div>
                                        <div class="order-col">
                                            <div><strong>TOTAL</strong></div>
                                            <div><strong class="order-total">{{order.get_total}}</strong></div>
                                        </div>
                                        {% endif %}
                                        
                                    </div>
                            
                                    
                                </div>
                                <!-- /Order Details -->
                            </div>
                            <!-- /row -->
                        </div>
                        <!-- /container -->
                    </div>					


{% endblock content %}

templates/base.html
<!DOCTYPE html>
<html>
{% include "head.html" %}

<body>

	{% include "header.html" %}
	{% if messages %}

	{% for message in messages %}
	<div class="alert alert-{{ message.tags }}" role="alert">
		{{ message }}
		<button type="button" class="close" data-dismiss="alert" aria-label="Close">
				<span aria-hidden="true">&times;</span>
			  </button>
	</div>
	
	{% endfor %}

{% endif %}
	{% block content %}
	{% endblock content %}
    {% block extra_body %}
    {% endblock %}


	{% include "scripts.html" %}

	{% include "footer.html" %}
</body>

templates/blank.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
		<!-- HEADER -->
	
		<!-- /HEADER -->

		<!-- NAVIGATION -->
		
		<!-- /NAVIGATION -->

		<!-- BREADCRUMB -->
		<div id="breadcrumb" class="section">
			<!-- container -->
			<div class="container">
				<!-- row -->
				<div class="row">
					<div class="col-md-12">
						<h3 class="breadcrumb-header">Regular Page</h3>
						<ul class="breadcrumb-tree">
							<li><a href="#">Home</a></li>
							<li class="active">Blank</li>
						</ul>
					</div>
				</div>
				<!-- /row -->
			</div>
			<!-- /container -->
		</div>
		<!-- /BREADCRUMB -->

		<!-- SECTION -->
		<div class="section">
			<!-- container -->
			<div class="container">
				<!-- row -->
				<div class="row">
				</div>
				<!-- /row -->
			</div>
			<!-- /container -->
		</div>
		<!-- /SECTION -->

		<!-- NEWSLETTER -->
		<div id="newsletter" class="section">
			<!-- container -->
			<div class="container">
				<!-- row -->
				<div class="row">
					<div class="col-md-12">
						<div class="newsletter">
							<p>Sign Up for the <strong>NEWSLETTER</strong></p>
							<form>
								<input class="input" type="email" placeholder="Enter Your Email">
								<button class="newsletter-btn"><i class="fa fa-envelope"></i> Subscribe</button>
							</form>
							<ul class="newsletter-follow">
								<li>
									<a href="#"><i class="fa fa-facebook"></i></a>
								</li>
								<li>
									<a href="#"><i class="fa fa-twitter"></i></a>
								</li>
								<li>
									<a href="#"><i class="fa fa-instagram"></i></a>
								</li>
								<li>
									<a href="#"><i class="fa fa-pinterest"></i></a>
								</li>
							</ul>
						</div>
					</div>
				</div>
				<!-- /row -->
			</div>
			<!-- /container -->
		</div>
		<!-- /NEWSLETTER -->

		<!-- FOOTER -->
	
		<!-- /FOOTER -->

		<!-- jQuery Plugins -->


{% endblock content %}

templates/footer.html
{% load static%}
<footer id="footer">
    <!-- top footer -->
    <div class="section">
        <!-- container -->
        <div class="container">
            <!-- row -->
            <div class="row">
                <div class="col-md-3 col-xs-6">
                   
                </div>

                <div class="col-md-3 col-xs-6">
                    <div class="footer">
                        
                    </div>
                </div>

                <div class="clearfix visible-xs"></div>

                <div class="col-md-3 col-xs-6">
                    <div class="footer">
                        
                    </div>
                </div>

                <div class="col-md-3 col-xs-6">
                    <div class="footer">
                        
                    </div>
                </div>
            </div>
            <!-- /row -->
        </div>
        <!-- /container -->
    </div>
    <!-- /top footer -->

    <!-- bottom footer -->
    <div id="bottom-footer" class="section">
        <div class="container">
            <!-- row -->
            <div class="row">
                <div class="col-md-12 text-center">
                    Electro Inc. all rights reserved 2017-2029
                    <span class="copyright">
                        <!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
                        Copyright &copy;<script>document.write(new Date().getFullYear());</script> All rights reserved | This template is made with <i class="fa fa-heart-o" aria-hidden="true"></i> by <a href="https://colorlib.com" target="_blank">Colorlib</a>
                    <!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
                    </span>


                </div>
            </div>
                <!-- /row -->
        </div>
        <!-- /container -->
    </div>
    <!-- /bottom footer -->
</footer>

templates/head.html
{% load static%}
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
     <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->

    <title>Electro - HTML Ecommerce Template</title>

     <!-- Google font -->
     <link href="https://fonts.googleapis.com/css?family=Montserrat:400,500,700" rel="stylesheet">

     <!-- Bootstrap -->
     <link type="text/css" rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}"/>

     <!-- Slick -->
     <link type="text/css" rel="stylesheet" href="{% static 'css/slick.css' %}"/>
     <link type="text/css" rel="stylesheet" href="{% static 'css/slick-theme.css' %}"/>

     <!-- nouislider -->
     <link type="text/css" rel="stylesheet" href="{% static 'css/nouislider.min.css' %}"/>

     <!-- Font Awesome Icon -->
     <link rel="stylesheet" href="{% static 'css/font-awesome.min.css' %}">

     <!-- Custom stlylesheet -->
     <link type="text/css" rel="stylesheet" href="{% static 'css/style.css' %}"/>

     <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
     <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
     <!--[if lt IE 9]>
       <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
       <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
     <![endif]-->
     <title>{% block head_title %}{% endblock %}</title>
     {% block extra_head %}
     {% endblock %}
</head>

templates/index.html
{% extends "base.html" %}
{% load static %}

{% block content %}
		<!-- HEADER -->
		
		<!-- /HEADER -->

		<!-- NAVIGATION -->

		<!-- /NAVIGATION -->

		<!-- SECTION -->

		<!-- /SECTION -->

		<!-- SECTION -->
		<div class="section">
			<!-- container -->
			<div class="container">
				<!-- row -->
				<div class="row">

					<!-- section title -->
					
					<!-- /section title -->

					<!-- Products tab & slick -->
					<div class="col-md-12">
						<div class="row">
							<div class="products-tabs">
								<!-- tab -->
								<div id="tab1" class="tab-pane active">
									<div class="products-slick" data-nav="#slick-nav-1">
										<!-- product -->
										{% for p in object_list %}
										<div class="product">
										
											<div class="product-img" >
												<img src="{{p.thumbnail.url}}" width="300px" height="300px">
												<div class="product-label">
													
													<span class="badge badge-pill {{p.get_label_display}}-color">NEW</span>
												</div>
											</div>
											<div class="product-body">
												{% for cat in p.categories.all %}
												<p class="product-category">{{cat}}</p>
												{% endfor %}
												<h3 class="product-name"><a href="{{p.get_absolute_url}}">{{p.title}}</a></h3>
												<h4 class="product-price">{{p.price}}<del class="product-old-price">$990.00</del></h4>
											
											
											</div>
											<div class="add-to-cart">
												<button class="add-to-cart-btn"><a href="{{p.get_add_to_cart_url}}"><i class="fa fa-shopping-cart"></i> add to cart</a></button>
											</div>
						
										</div>
										{% endfor %}
										<!-- /product -->

										<!-- product -->
										
										<!-- /product -->
									</div>
									<div id="slick-nav-1" class="products-slick-nav"></div>
								</div>
								<!-- /tab -->
							</div>
						</div>
					</div>
					<!-- Products tab & slick -->
				</div>
				<!-- /row -->
			</div>
			<!-- /container -->
		</div>
		<!-- /SECTION -->

		<!-- HOT DEAL SECTION -->
	
		<!-- /HOT DEAL SECTION -->


		
		

		<!-- NEWSLETTER -->
		<div id="newsletter" class="section">
			<!-- container -->

			<!-- /container -->
		</div>
		<!-- /NEWSLETTER -->

		<!-- FOOTER -->
	
		<!-- /FOOTER -->

		<!-- jQuery Plugins -->


{% endblock content %}

templates/order_summary.html
{% extends "base.html" %}
{% load cart_template_tags %}
{% load static%}
{% block content %}
<h2>Order Summary</h2>


<div class="table-responsive">
        <table class="table">
          <thead>
            <tr>
              <th scope="col">#</th>
              <th scope="col">Item Title</th>
              <th scope="col">Price</th>
              <th scope="col">Quantity</th>
              <th scope="col">Total </th>
            </tr>
          </thead>
          <tbody>
            {% for order_item in object.items.all %}
            <tr>
              <th scope="row">{{forloop.counter}}</th>
              <td>{{order_item.item.title}}</td>
              <td>{{order_item.item.price}}</td>
              <td>
                <a href="{% url 'remove_single_from_cart' order_item.item.slug %}">-&nbsp;</a>
                {{order_item.quantity}}
                <a href="{% url 'add_single_from_cart' order_item.item.slug %}">&nbsp;+</a>
              </td>
              <td>{{order_item.get_total_price}}</td>

            </tr>
            {% empty %}
            <tr>
              <td colspan="5">Your Cart is empty</td>

            </tr>
            <tr>
              <td colspan="5">
                <a class="btn btn-primary float-right" href="/">Continue Shopping</a>

              </td>

            </tr>
            {% endfor %}
            

          </tbody>
        </table>
        



        
      </div>
      {% if object.get_total %}
      <pre>
      <h3>Your grand total is $ {{object.get_total}}</h3>

      <strong>Continue Shopping </strong>  <a href="/"><button class="btn btn-primary">Continue Shopping</button></a> 
      
      <strong>Proceed to Checkout</strong>  <a href="{% url 'checkout'%}"><button class="btn btn-danger">Checkout</button></a>
      
      </pre>
      {% endif %}


      
{% endblock content %}

templates/scripts.html
{% load static%}
<script src="{% static 'js/jquery.min.js' %}"></script>
<script src="{% static 'js/bootstrap.min.js' %}"></script>
<script src="{% static 'js/slick.min.js' %}"></script>
<script src="{% static 'js/nouislider.min.js' %}"></script>
<script src="{% static 'js/jquery.zoom.min.js' %}"></script>
<script src="{% static 'js/main.js' %}"></script>

templates/search_results.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
<h2>Your search results!!</h2>
{% for result in queryset %}
    <a href="{{ result.get_absolute_url }}">{{ result.title }}</a>
{% endfor %}

{% endblock %}